Repository aaivu/ibat, pull requests merged in 2024-05, with the labels that each got.

#43 feat: Introduce `dt_df` parameter to `run_exp`
  examples/pipeline.py
  requirements.txt
  src/datasets/datasets.py
  src/pipeline.py
Labels: type/feature

#47 feat: Introduce scratch training
  README.md
  docs/images/archi-dig.png
  examples/pipeline.py
  src/pipeline.py
Labels: type/feature

#45 chore: Add setup.py
  README.md
  setup.py
Labels: type/chore

#49 chore: Add setup.cfg
  README.md
  setup.cfg
Labels: type/chore

#50 ci: Add pypi-publisher.yml
  .github/workflows/pypi-publisher.yml
  setup.py
Labels: type/cicd

#52 fix: Include csv within whl
  Makefile
  ibat/datasets/__init__.py
  ibat/datasets/_datasets/__init__.py
  ibat/pipeline.py
  setup.py
Labels: type/fix

#53 feat: Introduce use case for running time
  ibat/models/use_cases/__init__.py
  ibat/models/use_cases/running_time/__init__.py
  ibat/models/use_cases/running_time/bus/__init__.py
  ibat/models/use_cases/running_time/bus/mme4brt.py
Labels: type/feature
